# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('worker_id', models.SlugField(max_length=128, primary_key=True, serialize=False)),
                ('condition', models.PositiveIntegerField(default=0)),
                ('known', models.BooleanField(default=False)),
                ('num_pos_golds', models.PositiveIntegerField(default=0)),
                ('num_neg_golds', models.PositiveIntegerField(default=0)),
                ('num_pos_golds_correct', models.PositiveIntegerField(default=0)),
                ('num_neg_golds_correct', models.PositiveIntegerField(default=0)),
                ('num_hits', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
