# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 00:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hit_id', models.SlugField(max_length=128)),
                ('num_pos_golds', models.PositiveIntegerField(default=0)),
                ('num_neg_golds', models.PositiveIntegerField(default=0)),
                ('num_pos_golds_correct', models.PositiveIntegerField(default=0)),
                ('num_neg_golds_correct', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='worker',
            name='num_hits',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='num_neg_golds',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='num_neg_golds_correct',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='num_pos_golds',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='num_pos_golds_correct',
        ),
        migrations.AddField(
            model_name='hit',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.Worker'),
        ),
    ]
