# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_auto_20160524_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='hit',
            name='assignment_id',
            field=models.SlugField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
