# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_hit_assignment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hit',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
