# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_hit_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='hit',
            name='approved',
            field=models.NullBooleanField(default=None),
        ),
    ]
